package com.example.verificationInera.data.clinicalprocess.healthcond.description.getcaredocumentation._2.rivtabp21;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-09-17T14:00:33.441+02:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "GetCareDocumentationResponderService",
                  wsdlLocation = "file:/Users/tildakampman/Desktop/VerificationInera/src/main/resources/Inera/schemas/interactions/GetCareDocumentationInteraction/GetCareDocumentationInteraction_2.1_RIVTABP21.wsdl",
                  targetNamespace = "urn:riv:clinicalprocess:healthcond:description:GetCareDocumentation:2:rivtabp21")
public class GetCareDocumentationResponderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:riv:clinicalprocess:healthcond:description:GetCareDocumentation:2:rivtabp21", "GetCareDocumentationResponderService");
    public final static QName GetCareDocumentationResponderPort = new QName("urn:riv:clinicalprocess:healthcond:description:GetCareDocumentation:2:rivtabp21", "GetCareDocumentationResponderPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/tildakampman/Desktop/VerificationInera/src/main/resources/Inera/schemas/interactions/GetCareDocumentationInteraction/GetCareDocumentationInteraction_2.1_RIVTABP21.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetCareDocumentationResponderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/tildakampman/Desktop/VerificationInera/src/main/resources/Inera/schemas/interactions/GetCareDocumentationInteraction/GetCareDocumentationInteraction_2.1_RIVTABP21.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetCareDocumentationResponderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetCareDocumentationResponderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCareDocumentationResponderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetCareDocumentationResponderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetCareDocumentationResponderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetCareDocumentationResponderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GetCareDocumentationResponderInterface
     */
    @WebEndpoint(name = "GetCareDocumentationResponderPort")
    public GetCareDocumentationResponderInterface getGetCareDocumentationResponderPort() {
        return super.getPort(GetCareDocumentationResponderPort, GetCareDocumentationResponderInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCareDocumentationResponderInterface
     */
    @WebEndpoint(name = "GetCareDocumentationResponderPort")
    public GetCareDocumentationResponderInterface getGetCareDocumentationResponderPort(WebServiceFeature... features) {
        return super.getPort(GetCareDocumentationResponderPort, GetCareDocumentationResponderInterface.class, features);
    }

}
