package com.example.verificationInera.data.clinicalprocess.healthcond.description.getcaredocumentation._2.rivtabp21;

import com.example.verificationInera.data.clinicalprocess.healthcond.description.enums._2.ObjectFactory;
import com.example.verificationInera.data.clinicalprocess.healthcond.description.getcaredocumentationresponder._2.GetCareDocumentationResponseType;
import com.example.verificationInera.data.clinicalprocess.healthcond.description.getcaredocumentationresponder._2.GetCareDocumentationType;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-09-17T14:00:33.384+02:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "urn:riv:clinicalprocess:healthcond:description:GetCareDocumentation:2:rivtabp21", name = "GetCareDocumentationResponderInterface")
@XmlSeeAlso({com.example.verificationInera.data.clinicalprocess.healthcond.description.getcaredocumentationresponder._2.ObjectFactory.class, ObjectFactory.class, com.example.verificationInera.data.itintegration.registry._1.ObjectFactory.class, com.example.verificationInera.data.clinicalprocess.healthcond.description._2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetCareDocumentationResponderInterface {

    @WebMethod(operationName = "GetCareDocumentation", action = "urn:riv:clinicalprocess:healthcond:description:GetCareDocumentationResponder:2:GetCareDocumentation")
    @WebResult(name = "GetCareDocumentationResponse", targetNamespace = "urn:riv:clinicalprocess:healthcond:description:GetCareDocumentationResponder:2", partName = "parameters")
    public GetCareDocumentationResponseType getCareDocumentation(

        @WebParam(partName = "LogicalAddress", name = "LogicalAddress", targetNamespace = "urn:riv:itintegration:registry:1", header = true)
        String logicalAddress,
        @WebParam(partName = "parameters", name = "GetCareDocumentation", targetNamespace = "urn:riv:clinicalprocess:healthcond:description:GetCareDocumentationResponder:2")
        GetCareDocumentationType parameters
    );
}
